name: Test

on: workflow_dispatch
#  release:
#    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Install dependencies
      run: |
        yarn install
    - name: Build component-list
      run: |
        cd packages/component-list
        yarn build
    - name: Build web-extension
      run: |
        cd packages/web-extension
        yarn build
    - name: Publish to Chrome
      uses: trmcnvn/chrome-addon@v2
      with:
        extension: ${{ secrets.GWE_EXTENSION_ID }}
        zip: packages/web-extension/dist/web-extension.zip
        client-id: ${{ secrets.GWE_PUBLISH_CLIENT_ID }}
        client-secret: ${{ secrets.GWE_PUBLISH_CLIENT_SECRET }}
        refresh-token: ${{ secrets.GWE_PUBLISH_REFRESH_TOKEN }}